project:
  type: website

website:
  favicon: assets/favicon.ico
  google-analytics: G-CES9J82GLL
  page-footer: 
    center:
      - text: About
        href: about.qmd
      - text: License
        href: license.qmd
      - text: GitHub
        href: "https://github.com/berkeley-stat133"
    background: "dark"
  sidebar:
    style: "docked"
    title: "STAT 133 <br><small>Spring 2025</small>"
    logo: assets/stat_bear.png
    logo-alt: "UC Berkeley Statistics logo"
    tools:
      - icon: github
        href: https://github.com/berkeley-stat133/spring-2025
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: about.qmd
        text: About
      - section: "Units"
        contents:
          - units/unit1.qmd
          - units/unit2.qmd
          - units/unit3.qmd
          - units/unit4.qmd
          - units/unit5.qmd
          - units/unit6.qmd
          - units/unit7.qmd
          - units/unit8.qmd
          - units/unit9.qmd
          - units/unit10.qmd
          - units/unit11.qmd
          - units/unit12.qmd
          - units/unit13.qmd
          - units/unit14.qmd
      - section: "Other"
        contents:
          - href: staff.qmd
            text: Staff
          - href: cheatsheets.qmd
            text: Cheatsheets
          - href: email.qmd
            text: Email
          - href: ed-netiquette.qmd
            text: "Ed Netiquette"
          - href: faqs.qmd
            text: FAQs
          - href: five-things.qmd
            text: "5 Things to know"
          - href: license.qmd
            text: License

format:
  html:
    theme: lumen
    fontsize: 1em
    css: assets/styles.css
    toc: true



